In [1]:
import numpy as np

In [9]:
l=[1,2,3,4,5,6]
type(l)

list

# generating array

In [4]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [8]:
type(np.array(l))

numpy.ndarray

In [5]:
l1=[4,5,6,"sudh",34.456,True]

In [14]:
a1=np.array(l1) # converted each and every data type in hiher oder i.e here it is str

In [7]:
1#differ in data type

In [10]:
# it is called as array but it is similar to list

In [15]:
a2=np.array([[1,2,3],[4,5,6]])#2d array

In [16]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [17]:
a1

array(['4', '5', '6', 'sudh', '34.456', 'True'], dtype='<U32')

In [18]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# find the dimension

In [21]:
#find the dimension (as we do data manupulation we need same dimension of data )
a1.ndim # to plot it we need only one axis

1

In [22]:
a2.ndim# require 2dimension to represent it

2

In [23]:
a3.ndim# 3 axis  are needed to represent the data

3

 # size

In [24]:
a1.size # .size give you the total number of elements

6

In [25]:
a2.size

6

In [26]:
a3.sizea

9

 # shape

In [27]:
a1.shape 

(6,)

In [29]:
a2.shape# 2 rows and 3 columns


(2, 3)

In [30]:
a3.shape #  3X3 one such kind of matrices 

(1, 3, 3)

# generate radom data

In [33]:
np.random.randint(2,5) # generating random data between 2 to 5

4

In [34]:
np.random.randint(2,15)

8

In [36]:
#generate data in spectific dimension

np.random.randint(2,50,(3,4)) # data with 3 rows and 4 columns

array([[25, 23, 31, 24],
       [ 9, 10, 23, 17],
       [41, 10, 11,  4]])

In [37]:
np.random.randint(2,50,(2,3,4)) #3X4 two such kind of matrices 

array([[[44, 37, 33, 37],
        [ 5,  9, 30,  9],
        [12, 26, 28,  5]],

       [[ 2, 36, 25, 39],
        [ 6, 16,  6, 21],
        [39, 16,  4, 34]]])

# rand

In [39]:
np.random.rand(2,3) # generate random number  of  2x3
# any kind od mean and any kind of sd

array([[0.62522626, 0.20497788, 0.28539095],
       [0.14039442, 0.19706216, 0.01392393]])

# randn

In [43]:
a4=np.random.randn(4,4) #standard normal distribution  sd=1 ,mean=0

In [44]:
a4
# average of a column will be equal to 0

array([[-0.4711697 , -0.6067999 ,  0.80363903,  0.51133606],
       [-0.72060455, -0.19727402, -0.30094835, -1.59781344],
       [-0.45436015, -0.50873556, -0.40597073, -0.30616715],
       [-1.4775772 ,  0.9564439 , -0.08810383, -0.97138176]])

# reshape

In [ ]:
# number of data points going to remane same ont dimension will change


In [45]:
a4.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [47]:
# 3x4=12 but 4x4=16
a4.reshape(2,8)


array([[-0.4711697 , -0.6067999 ,  0.80363903,  0.51133606, -0.72060455,
        -0.19727402, -0.30094835, -1.59781344],
       [-0.45436015, -0.50873556, -0.40597073, -0.30616715, -1.4775772 ,
         0.9564439 , -0.08810383, -0.97138176]])

In [48]:
a4.reshape(8,2)

array([[-0.4711697 , -0.6067999 ],
       [ 0.80363903,  0.51133606],
       [-0.72060455, -0.19727402],
       [-0.30094835, -1.59781344],
       [-0.45436015, -0.50873556],
       [-0.40597073, -0.30616715],
       [-1.4775772 ,  0.9564439 ],
       [-0.08810383, -0.97138176]])

In [49]:
a4.reshape(16,1)

array([[-0.4711697 ],
       [-0.6067999 ],
       [ 0.80363903],
       [ 0.51133606],
       [-0.72060455],
       [-0.19727402],
       [-0.30094835],
       [-1.59781344],
       [-0.45436015],
       [-0.50873556],
       [-0.40597073],
       [-0.30616715],
       [-1.4775772 ],
       [ 0.9564439 ],
       [-0.08810383],
       [-0.97138176]])

In [51]:
a4.reshape(2,-1) # if  we write negative number it will automatically detect the shape

array([[-0.4711697 , -0.6067999 ,  0.80363903,  0.51133606, -0.72060455,
        -0.19727402, -0.30094835, -1.59781344],
       [-0.45436015, -0.50873556, -0.40597073, -0.30616715, -1.4775772 ,
         0.9564439 , -0.08810383, -0.97138176]])

In [52]:
a4.reshape(2,2,4)

array([[[-0.4711697 , -0.6067999 ,  0.80363903,  0.51133606],
        [-0.72060455, -0.19727402, -0.30094835, -1.59781344]],

       [[-0.45436015, -0.50873556, -0.40597073, -0.30616715],
        [-1.4775772 ,  0.9564439 , -0.08810383, -0.97138176]]])

In [53]:
a4.reshape(1,2,2,4)

array([[[[-0.4711697 , -0.6067999 ,  0.80363903,  0.51133606],
         [-0.72060455, -0.19727402, -0.30094835, -1.59781344]],

        [[-0.45436015, -0.50873556, -0.40597073, -0.30616715],
         [-1.4775772 ,  0.9564439 , -0.08810383, -0.97138176]]]])

# etract data

In [58]:
a1

array(['4', '5', '6', 'sudh', '34.456', 'True'], dtype='<U32')

In [55]:
a1[0]

'4'

In [57]:
a1[2:6] # also it exclude the upper bound

array(['6', 'sudh', '34.456', 'True'], dtype='<U32')

In [60]:
a1[2:6:2] # start from 2 , end at 6 and take jump of 2

array(['6', '34.456'], dtype='<U32')

In [61]:
a1[::-1] # reverse the array

array(['True', '34.456', 'sudh', '6', '5', '4'], dtype='<U32')

In [63]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
# extract 1,2,3
a2[0]

array([1, 2, 3])

# slicing 

In [70]:
a2[:,1:]# slicing 

array([[2, 3],
       [5, 6]])

In [71]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [74]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [78]:
a5=np.random.randint(2,90,(6,5))

In [79]:
a5

array([[50, 82, 75, 28, 34],
       [76, 17, 20, 20, 54],
       [57, 38, 22, 65, 62],
       [25, 80, 34, 10, 25],
       [ 7, 37, 87,  5, 70],
       [10, 29, 63, 85, 22]])

In [80]:
# filter all the records with value more than 40
a5[a5>40]

array([50, 82, 75, 76, 54, 57, 65, 62, 80, 87, 70, 63, 85])

In [81]:
# changing data
a5

array([[50, 82, 75, 28, 34],
       [76, 17, 20, 20, 54],
       [57, 38, 22, 65, 62],
       [25, 80, 34, 10, 25],
       [ 7, 37, 87,  5, 70],
       [10, 29, 63, 85, 22]])

In [84]:
a5[0][1]

82

In [85]:
a5[0][1]= 100

In [86]:
a5

array([[ 50, 100,  75,  28,  34],
       [ 76,  17,  20,  20,  54],
       [ 57,  38,  22,  65,  62],
       [ 25,  80,  34,  10,  25],
       [  7,  37,  87,   5,  70],
       [ 10,  29,  63,  85,  22]])

In [92]:
a6=np.random.randint(0,3,(3,3))

In [93]:
a7=np.random.randint(0,3,(3,3))

In [94]:
a6

array([[1, 1, 2],
       [0, 1, 2],
       [0, 0, 0]])

In [95]:
a7

array([[2, 0, 1],
       [1, 2, 0],
       [2, 1, 1]])

# operations 

In [96]:
a6 * a7  # element  multipication

array([[2, 0, 2],
       [0, 2, 0],
       [0, 0, 0]])

In [97]:
a6@a7 # matrix multipication

array([[7, 4, 3],
       [5, 4, 2],
       [0, 0, 0]])

In [99]:
a6

array([[1, 1, 2],
       [0, 1, 2],
       [0, 0, 0]])

In [101]:

a6+100 # add 100 with every element

array([[101, 101, 102],
       [100, 101, 102],
       [100, 100, 100]])

In [103]:
a6*6

array([[ 6,  6, 12],
       [ 0,  6, 12],
       [ 0,  0,  0]])

In [102]:
a6/0

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [nan, inf, inf],
       [nan, nan, nan]])

In [104]:
a6

array([[1, 1, 2],
       [0, 1, 2],
       [0, 0, 0]])

In [105]:
# power operation
a6**6

array([[ 1,  1, 64],
       [ 0,  1, 64],
       [ 0,  0,  0]], dtype=int32)

In [110]:
a8=np.zeros((4,4))

In [111]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
a9=np.ones((4,5))

In [114]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [118]:
#adding array with array
#broadcasting- rowise addition operation
a9+np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [119]:
a9+np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [120]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [121]:
#broadcasting- columnwise addition operation
np.array([1,2,3,4]).T # rotating it column wise first

array([1, 2, 3, 4])

In [122]:
a9+np.array([1,2,3,4]).T

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [123]:
#we need 2d data to do transpose operation 

In [126]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [124]:
a9+np.array([[1,2,3,4]]).T

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [129]:
a6

array([[1, 1, 2],
       [0, 1, 2],
       [0, 0, 0]])

In [128]:
a6.T

array([[1, 0, 0],
       [1, 1, 0],
       [2, 2, 0]])

In [130]:
a5

array([[ 50, 100,  75,  28,  34],
       [ 76,  17,  20,  20,  54],
       [ 57,  38,  22,  65,  62],
       [ 25,  80,  34,  10,  25],
       [  7,  37,  87,   5,  70],
       [ 10,  29,  63,  85,  22]])

In [132]:
np.sqrt(a5)

array([[ 7.07106781, 10.        ,  8.66025404,  5.29150262,  5.83095189],
       [ 8.71779789,  4.12310563,  4.47213595,  4.47213595,  7.34846923],
       [ 7.54983444,  6.164414  ,  4.69041576,  8.06225775,  7.87400787],
       [ 5.        ,  8.94427191,  5.83095189,  3.16227766,  5.        ],
       [ 2.64575131,  6.08276253,  9.32737905,  2.23606798,  8.36660027],
       [ 3.16227766,  5.38516481,  7.93725393,  9.21954446,  4.69041576]])

In [133]:
np.exp(a5)

array([[5.18470553e+21, 2.68811714e+43, 3.73324200e+32, 1.44625706e+12,
        5.83461743e+14],
       [1.01480039e+33, 2.41549528e+07, 4.85165195e+08, 4.85165195e+08,
        2.83075330e+23],
       [5.68572000e+24, 3.18559318e+16, 3.58491285e+09, 1.69488924e+28,
        8.43835667e+26],
       [7.20048993e+10, 5.54062238e+34, 5.83461743e+14, 2.20264658e+04,
        7.20048993e+10],
       [1.09663316e+03, 1.17191424e+16, 6.07603023e+37, 1.48413159e+02,
        2.51543867e+30],
       [2.20264658e+04, 3.93133430e+12, 2.29378316e+27, 8.22301271e+36,
        3.58491285e+09]])

In [138]:
np.log10(a5)

array([[1.69897   , 2.        , 1.87506126, 1.44715803, 1.53147892],
       [1.88081359, 1.23044892, 1.30103   , 1.30103   , 1.73239376],
       [1.75587486, 1.5797836 , 1.34242268, 1.81291336, 1.79239169],
       [1.39794001, 1.90308999, 1.53147892, 1.        , 1.39794001],
       [0.84509804, 1.56820172, 1.93951925, 0.69897   , 1.84509804],
       [1.        , 1.462398  , 1.79934055, 1.92941893, 1.34242268]])

In [142]:
range(10)

range(0, 10)

In [139]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [140]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

# generating data

In [141]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
np.arange(1,10,0.5) # accept floating point numbers

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [148]:
np.linspace(2,3,num=50) # generate 2 and 3 generate 50 numbers (equal segments)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [149]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [151]:
np.logspace(2,3,num=5,base=10)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [153]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])