In [2]:
import pandas as pd

In [1]:
# all about data manuplation

In [2]:
# operation --> join , merge , concatation

In [18]:
data={'name':['sudh','krish','hitesh','tulesko'],
     "salary":[100,200,300,400],
     'mail_id':["sudh@ineuron.ai","krish@ineuron.ai","hiyes@ineuron.ai","tulesh@ineuron.ai"],
       'addr':['blr','blr','blr','mum']}

In [4]:
# dict to dataframe

In [5]:
pd.DataFrame(data)

name  salary            mail_id addr
0     sudh     100    sudh@ineuron.ai  blr
1    krish     200   krish@ineuron.ai  blr
2   hitesh     300   hiyes@ineuron.ai  blr
3  tulesko     400  tulesh@ineuron.ai  mum

In [6]:
data1={'name':['sudh','krish','hitesh','tulesko','ccx'],
     "salary":[100,200,300,400],
     'mail_id':["sudh@ineuron.ai","krish@ineuron.ai","hiyes@ineuron.ai","tulesh@ineuron.ai"],
       'addr':['blr','blr','blr','mum']}

In [7]:
pd.DataFrame(data1)

ValueError: All arrays must be of the same length

In [ ]:
# all the values in the dict should be of same length

In [ ]:
df=pd.DataFrame(data)

In [ ]:
pd.DataFrame(data,columns=[0,1,2,3])

In [8]:
# my own indexes
pd.DataFrame(data,index=[4,5,6,7])

name  salary            mail_id addr
4     sudh     100    sudh@ineuron.ai  blr
5    krish     200   krish@ineuron.ai  blr
6   hitesh     300   hiyes@ineuron.ai  blr
7  tulesko     400  tulesh@ineuron.ai  mum

In [13]:
pd.DataFrame(data,index=[4,5,6,7]).loc[5:6]

name  salary           mail_id addr
5   krish     200  krish@ineuron.ai  blr
6  hitesh     300  hiyes@ineuron.ai  blr

In [11]:
# not able to extract using mentioned  indexes using iloc
pd.DataFrame(data,index=[4,5,6,7]).iloc[4:6]

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [10]:
pd.DataFrame(data,index=[4,5,6,7]).iloc[1:3]

name  salary           mail_id addr
5   krish     200  krish@ineuron.ai  blr
6  hitesh     300  hiyes@ineuron.ai  blr

In [ ]:
#iloc ---> goes after default indexes
#loc ----> goes after named indexes


In [14]:
# we can also give indexes as str
pd.DataFrame(data,index=["hi","bhsb","prik","yololo"])

name  salary            mail_id addr
hi         sudh     100    sudh@ineuron.ai  blr
bhsb      krish     200   krish@ineuron.ai  blr
prik     hitesh     300   hiyes@ineuron.ai  blr
yololo  tulesko     400  tulesh@ineuron.ai  mum

In [21]:
data1=pd.DataFrame(data,index=[0,1,2,3])

In [22]:
data1

name  salary            mail_id addr
0     sudh     100    sudh@ineuron.ai  blr
1    krish     200   krish@ineuron.ai  blr
2   hitesh     300   hiyes@ineuron.ai  blr
3  tulesko     400  tulesh@ineuron.ai  mum

In [25]:
d={"pf_nu":[223,23,221323,223],
   "incom _tax":[234,232,767,6778],
   "mobile_no": [2345,3255,34,342422],
   "courses":["ds","bigdata","web dev","blockchain"]}


In [26]:
data2=pd.DataFrame(d)

In [27]:
data2

pf_nu  incom _tax  mobile_no     courses
0     223         234       2345          ds
1      23         232       3255     bigdata
2  221323         767         34     web dev
3     223        6778     342422  blockchain

In [28]:
# operations

# concatination 


In [30]:
# merge vertically   and merge horizontally

In [32]:
pd.concat([data1,data2]) # here by default axis =0 i.e vertical concatation
# diagonal ---> why
# because i have not given the coustom indexs in the second data frame

name  salary            mail_id addr     pf_nu  incom _tax  mobile_no  \
0     sudh   100.0    sudh@ineuron.ai  blr       NaN         NaN        NaN   
1    krish   200.0   krish@ineuron.ai  blr       NaN         NaN        NaN   
2   hitesh   300.0   hiyes@ineuron.ai  blr       NaN         NaN        NaN   
3  tulesko   400.0  tulesh@ineuron.ai  mum       NaN         NaN        NaN   
0      NaN     NaN                NaN  NaN     223.0       234.0     2345.0   
1      NaN     NaN                NaN  NaN      23.0       232.0     3255.0   
2      NaN     NaN                NaN  NaN  221323.0       767.0       34.0   
3      NaN     NaN                NaN  NaN     223.0      6778.0   342422.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [33]:
#removing  custom indexes
data1=pd.DataFrame(data)


In [35]:

pd.concat([data1,data2])

name  salary            mail_id addr     pf_nu  incom _tax  mobile_no  \
0     sudh   100.0    sudh@ineuron.ai  blr       NaN         NaN        NaN   
1    krish   200.0   krish@ineuron.ai  blr       NaN         NaN        NaN   
2   hitesh   300.0   hiyes@ineuron.ai  blr       NaN         NaN        NaN   
3  tulesko   400.0  tulesh@ineuron.ai  mum       NaN         NaN        NaN   
0      NaN     NaN                NaN  NaN     223.0       234.0     2345.0   
1      NaN     NaN                NaN  NaN      23.0       232.0     3255.0   
2      NaN     NaN                NaN  NaN  221323.0       767.0       34.0   
3      NaN     NaN                NaN  NaN     223.0      6778.0   342422.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [36]:
pd.concat([data1,data2],axis=1) # this actual horizontal concatation i.e rowwise


name  salary            mail_id addr   pf_nu  incom _tax  mobile_no  \
0     sudh     100    sudh@ineuron.ai  blr     223         234       2345   
1    krish     200   krish@ineuron.ai  blr      23         232       3255   
2   hitesh     300   hiyes@ineuron.ai  blr  221323         767         34   
3  tulesko     400  tulesh@ineuron.ai  mum     223        6778     342422   

      courses  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [38]:
 pd.concat([data1,data2],axis=0) # rowwise  ---> vertical concatation

name  salary            mail_id addr     pf_nu  incom _tax  mobile_no  \
0     sudh   100.0    sudh@ineuron.ai  blr       NaN         NaN        NaN   
1    krish   200.0   krish@ineuron.ai  blr       NaN         NaN        NaN   
2   hitesh   300.0   hiyes@ineuron.ai  blr       NaN         NaN        NaN   
3  tulesko   400.0  tulesh@ineuron.ai  mum       NaN         NaN        NaN   
0      NaN     NaN                NaN  NaN     223.0       234.0     2345.0   
1      NaN     NaN                NaN  NaN      23.0       232.0     3255.0   
2      NaN     NaN                NaN  NaN  221323.0       767.0       34.0   
3      NaN     NaN                NaN  NaN     223.0      6778.0   342422.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [ ]:
# here it is giving Nan ---> as the column names are different

In [39]:
d1={"0":[223,23,221323,223],
   "1":[234,232,767,6778],
   "2": [2345,3255,34,342422],
   "3":["ds","bigdata","web dev","blockchain"]}

In [41]:
d2={'0':['sudh','krish','hitesh','tulesko'],
     "1":[100,200,300,400],
     '2':["sudh@ineuron.ai","krish@ineuron.ai","hiyes@ineuron.ai","tulesh@ineuron.ai"],
       '3':['blr','blr','blr','mum']}

In [42]:
df1=pd.DataFrame(d1)

In [43]:
df2=pd.DataFrame(d2)

In [47]:
pd.concat([df1,df2])

0     1                  2           3
0      223   234               2345          ds
1       23   232               3255     bigdata
2   221323   767                 34     web dev
3      223  6778             342422  blockchain
0     sudh   100    sudh@ineuron.ai         blr
1    krish   200   krish@ineuron.ai         blr
2   hitesh   300   hiyes@ineuron.ai         blr
3  tulesko   400  tulesh@ineuron.ai         mum

In [48]:
#here column name is same 

# merge 

In [50]:
d3={
    "emp_id":[101,102,103,104],
    "salary":[234,234,434,400],
    "pf":[23,45,67,89],
}

In [52]:
d4={
    "emp_id":[101,102,104,105],
    "mobile_no":[2312,123323,12323,123232434],
    "house_nu":[345,354,444,67],
    
}

In [53]:
df3=pd.DataFrame(d3)

In [54]:
df4=pd.DataFrame(d4)

In [55]:
df3


emp_id  salary  pf
0     101     234  23
1     102     234  45
2     103     434  67
3     104     400  89

In [57]:
df4

emp_id  mobile_no  house_nu
0     101       2312       345
1     102     123323       354
2     104      12323       444
3     105  123232434        67

In [58]:
# some how these two data frame are related to each other


In [59]:
# merge and join opeation in pandas

In [60]:
# merge
pd.merge(df3,df4) # by default it is performing inner merge operation

emp_id  salary  pf  mobile_no  house_nu
0     101     234  23       2312       345
1     102     234  45     123323       354
2     104     400  89      12323       444

In [61]:
# it is taking the commen one ---> in emp_id

In [62]:
pd.merge(df3,df4 ,how ="left")  #left merge every thing from left
                                 # here left data is df3
    # here it is taking everything from df3 and then performing merge operation

emp_id  salary  pf  mobile_no  house_nu
0     101     234  23     2312.0     345.0
1     102     234  45   123323.0     354.0
2     103     434  67        NaN       NaN
3     104     400  89    12323.0     444.0

In [63]:
pd.merge(df3,df4 ,how ="right") #right  merge every thing from left
                                 # here right data is df4
    # here it is taking everything from df4 and then performing merge operation

emp_id  salary    pf  mobile_no  house_nu
0     101   234.0  23.0       2312       345
1     102   234.0  45.0     123323       354
2     104   400.0  89.0      12323       444
3     105     NaN   NaN  123232434        67

In [65]:
# specify on waht you are going to do join opeartion ---> that is providing the column name

In [68]:
pd.merge(df3,df4 ,how ="right",on="emp_id")

emp_id  salary    pf  mobile_no  house_nu
0     101   234.0  23.0       2312       345
1     102   234.0  45.0     123323       354
2     104   400.0  89.0      12323       444
3     105     NaN   NaN  123232434        67

In [69]:
d5={
    "emp_id1":[101,102,103,104],
    "salary":[234,234,434,400],
    "pf":[23,45,67,89],
}
d6={
    "emp_id2":[101,102,104,105],
    "mobile_no":[2312,123323,12323,123232434],
    "house_nu":[345,354,444,67],
    
}

In [71]:
df5=pd.DataFrame(d5)

In [72]:
df6=pd.DataFrame(d6)

In [74]:
pd.merge(df5,df6)
# No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False


MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [76]:
#so ho to do it when column is not same but the data inside the column refering to each other


In [80]:
pd.merge(df5,df6 ,how ="inner",left_on="emp_id1",right_on="emp_id2")

emp_id1  salary  pf  emp_id2  mobile_no  house_nu
0      101     234  23      101       2312       345
1      102     234  45      102     123323       354
2      104     400  89      104      12323       444

In [81]:
#merge operation are done based on the comaprison  of keys values and type of merge

In [ ]:
# merge opertation base on two different keys

In [83]:
d7={
    "emp_id":[101,102,103,104],
    "salary":[234,234,434,400],
    "pf":[23,45,67,89],
}
d8={
    "emp_id":[101,102,104,105],
    "salary":[2312,234,234,434],
    "house_nu":[345,354,444,67],
    
}

In [84]:
df7=pd.DataFrame(d7)
df8=pd.DataFrame(d8)

In [85]:
df7

emp_id  salary  pf
0     101     234  23
1     102     234  45
2     103     434  67
3     104     400  89

In [86]:
df8

emp_id  salary  house_nu
0     101    2312       345
1     102     234       354
2     104     234       444
3     105     434        67

In [ ]:
#merge operation base on two columns

In [89]:
pd.merge(df7,df8,on=["emp_id","salary"])
# it will give commen for both the columns then it will do merge

emp_id  salary  pf  house_nu
0     102     234  45       354

In [90]:
d9={
    "emp_id":[101,102,103,104],
    "salary":[234,234,434,400],
    "pf":[23,45,67,89],
}
d10={
    "emp_id":[101,102,104,105,433],
    "salary":[2312,234,234,434,33],
    "house_nu":[345,354,444,67,66],
    
}


# suppose if we have 1 more row  in d10 then what will happen

In [91]:
df9=pd.DataFrame(d9)
df10=pd.DataFrame(d10)

In [92]:
pd.merge(df9,df10,on=["emp_id","salary"])
# dimension not going to affect the operation

emp_id  salary  pf  house_nu
0     102     234  45       354

# join opeartion

In [102]:
d9={
    "emp_id1":[101,102,103,104],
    "salary1":[234,234,434,400],
    "pf":[23,45,67,89],
}
d10={
    "emp_id2":[101,102,104,105,433],
    "salary2":[2312,234,234,434,33],
    "house_nu":[345,354,444,67,66],
    
}

df9=pd.DataFrame(d9,index=["a","b","c","d"])
df10=pd.DataFrame(d10,index=["a","b","d","e","f"])

In [103]:
df9

emp_id1  salary1  pf
a      101      234  23
b      102      234  45
c      103      434  67
d      104      400  89

In [104]:
df10

emp_id2  salary2  house_nu
a      101     2312       345
b      102      234       354
d      104      234       444
e      105      434        67
f      433       33        66

In [105]:
df9.join(df10)
# matching on indexes
#join operation is similar to merge

# merge operation ---->it is trying to perform based on the column name
#join operation ----> it istrying to perform based on indexes---> row indexes


emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0   2312.0     345.0
b      102      234  45    102.0    234.0     354.0
c      103      434  67      NaN      NaN       NaN
d      104      400  89    104.0    234.0     444.0

In [106]:
data=pd.read_csv(r"D:\full_stack\material\pandas_day2\sales_data_final.csv")

In [107]:
data.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

# derive column based on existing column

In [108]:
# create new column  -- profit flag to store pos or neg based on the profit column

In [111]:
def pos_flag(a):
    if a>0:
        return "positive"
    else:
        return "negative"

In [112]:
pos_flag(45)

'positive'

In [ ]:
# so we can use "apply function"



In [115]:
data["profit_fag"]=data["profit"].apply(pos_flag)

In [113]:
#or
data["profit_fag_"]=data["profit"]>0

In [116]:
data.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  profit_fag_ profit_fag  
0          35.46          Medium  2011         True   positive  
1           9.72          Medium  2011         True   positive  
2           8.17            High  2011         True   positive  
3           4.82            High  2011        False   negative  
4           4.70          Medium  2011         True   positive  

[5 rows x 23 columns]

In [117]:
#create one more column where you can store length of customer_name

SyntaxError: invalid syntax (4031523941.py, line 1)

In [120]:
data["len_customer_name"]=data["customer_name"].apply(len)

In [121]:
data.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  profit_fag_  \
0        2      0.0  106.140         35.46          Medium  2011         True   
1        3      0.1   36.036          9.72          Medium  2011         True   
2        4      0.0   29.640          8.17            High  2011         True   
3        3      0.5  -26.055          4.82            High  2011        False   
4        5      0.1   37.770          4.70          Medium  2011         True   

   profit_fag len_customer_name  
0    positive                15  
1    positive                11  
2    positive                13  
3    negative                12  
4    positive                11  

[5 rows x 24 columns]

In [122]:
# lets filter out some value 

#categorise the qunatity in 3 segments
'''1 high 
2 medium
3 low'''

In [124]:
def quant(a):
    if a<10:
        return "low"
    elif a>10 and a<20 :
        return "medium"
    elif a>20:
        return "high"

In [125]:
data["flag_quantit"]=data["quantity"].apply(quant)

In [126]:
data.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  profit_fag_  \
0      0.0  106.140         35.46         Medium  2011         True   
1      0.1   36.036          9.72         Medium  2011         True   
2      0.0   29.640          8.17           High  2011         True   
3      0.5  -26.055          4.82           High  2011        False   
4      0.1   37.770          4.70         Medium  2011         True   

   profit_fag  len_customer_name flag_quantit  
0    positive                 15          low  
1    positive                 11          low  
2    positive                 13          low  
3    negative                 12          low  
4    positive                 11          low  

[5 rows x 25 columns]

In [128]:
data["sq_quantity"]=data["quantity"].apply(lambda a: a**2)

In [129]:
data.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... discount  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      0.0   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...      0.1   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      0.0   
3  Home Office        Stockholm     Sweden      EU    North  ...      0.5   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...      0.1   

    profit shipping_cost order_priority  year  profit_fag_  profit_fag  \
0  106.140         35.46         Medium  2011         True    positive   
1   36.036          9.72         Medium  2011         True    positive   
2   29.640          8.17           High  2011         True    positive   
3  -26.055          4.82           High  2011        False    negative   
4   37.770          4.70         Medium  2011         True    positive   

   len_customer_name  flag_quantit sq_quantity  
0                 15           low           4  
1                 11           low           9  
2                 13           low          16  
3                 12           low           9  
4                 11           low          25  

[5 rows x 26 columns]

# numpy

In [130]:
import numpy as np

In [131]:
np.array([1,2,3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

In [133]:
type(np.array([1,2,3,4,5,6,7]))

numpy.ndarray

In [143]:

np.array([[1,2,3],[1,2,3]]) # 2d array

array([[1, 2, 3],
       [1, 2, 3]])

In [145]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
l=[[1,2,3,4],[5,6,7,8]]

In [148]:
l[0][0]

1

In [151]:
a=np.array([1,2,3,4,5],ndmin=5)

In [152]:
a

array([[[[[1, 2, 3, 4, 5]]]]])

In [162]:
arr=np.array([[1,2,3],[2,3,4],[6,7,8]])

In [163]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8]])

In [165]:
arr.ndim

2

In [166]:
# 3d array

In [169]:
np.random.randint(1,5,(4,4))

array([[2, 1, 3, 1],
       [2, 1, 3, 4],
       [2, 3, 3, 4],
       [2, 1, 3, 4]])

In [180]:
np.random.randint(1,10,(4,4,2))

array([[[2, 4],
        [9, 3],
        [9, 3],
        [2, 6]],

       [[1, 4],
        [9, 1],
        [5, 3],
        [4, 7]],

       [[5, 5],
        [3, 5],
        [2, 6],
        [5, 9]],

       [[2, 5],
        [4, 9],
        [5, 8],
        [1, 4]]])

In [ ]:
#Task 1 - Fitbit Dataset

1. Read this dataset in pandas , mysql and mongodb 
2. while creting a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql
 ## hint - use csvkit library to automate this task and to load a data in bulk in you mysql 
3. convert all the dates avaible in dataset to timestamp format in pandas and in sql you to convert it in date format
4 . Find out in this data that how many unique id's we have 
5 . which id is one of the active id that you have in whole dataset 
6 . how many of them have not logged there activity find out in terms of number of ids 
7 . Find out who is the laziest person id that we have in dataset 
8 . Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset 
9. how many person are not a regular person with respect to activity try to find out those 
10 . who is the thired most active person in this dataset find out those in pandas and in sql both . 
11 . who is the 5th most laziest person avilable in dataset find it out 
12 . what is a totla acumulative calories burn for a person find out 


In [ ]:
#task 2 - Superstore_USA
1 . load this data in sql and in pandas with a relation in sql 
2 . while loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table 
3 . Find out how return that we ahve recived and with a product id 
4 . try  to join order and return data both in sql and pandas 
5 . Try to find out how many unique customer that we have 
6 . try to find out in how many regions we are selling a product and who is a manager for a respective region 
7 . find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset 
8 . Create a new coulmn and try to find our a diffrence between order date and shipment date
9 . base on question number 8 find out for which order id we have shipment duration more than 10 days 
10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well 
11 . Gorup by region and find out which region is more profitable 
12 . Try to find out overalll in which country we are giving more didscount 
13 . Give me a list of unique postal code 
14 . which customer segement is more profitalble find it out . 
15 . try to find out the 10th most loss making product catagory . 
16 . Try to find out 10 top  product with highest margins 

submit your git link for the same 
 
you have to submit this task by next Friday 5th 11PM IST  to respective mail id 
sudhanshu@ineuron.ai , sunny.savita@ineuron.ai 
