In [1]:
import random

random.random() # random.random returns a random number between 0 and 1

0.6600341089166547

In [4]:
random.uniform(1, 10)  # random.uniform (1, 10) returns a random floating number between 1 and 10

3.543208968550143

In [5]:
random.randint(1, 10) # random.randint will return a random integer N such that a <= N <= b

1

In [6]:
random.randrange(1, 10) # random.randrange returns a random integer N such that a <= N < b

1

In [7]:
random.normalvariate(0,1) # random.normalvariate returns a random floating point number N with mean as 0 and standard deviation as 1

0.32131960134575466

In [9]:
mylist =   list("ABCDEFGH")
a = random.choice(mylist) # random.choice returns a random element from a sequence
print(a)

b = random.sample(mylist, 3) # random.sample returns a list of unique elements chosen from the list, sequence, or set, we passed as an argument
print(b)



A
['D', 'F', 'A']


In [14]:
random.choices(mylist,k=3) # random.choices (mylist,3) returns a list of elements chosen from the list, sequence, or set, we passed as an argument.
#The elements can be repeated from the list, sequence, or set.

['H', 'E', 'F']

In [15]:
random.shuffle(mylist) # random.shuffle shuffles the elements in the list in place

In [16]:
mylist

['A', 'B', 'H', 'G', 'F', 'E', 'C', 'D']

In [22]:
random.seed(10) # random.seed will generate the same random number every time we run the code
print(random.random())
print(random.randint(1, 10))
random.seed(10)
print(random.random())
print(random.randint(1, 10))

0.5714025946899135
7
0.5714025946899135
7


In [24]:
random.seed(2) 
print(random.random())
print(random.randint(1, 10))
random.seed(2)
print(random.random())
print(random.randint(1, 10))

0.9560342718892494
1
0.9560342718892494
1


## mylist

In [35]:
# these number are reproducible so it is not used for security purposes

import secrets
mylist = list("ABCDEFGH")
print(secrets.randbelow(10)) # secrets.randbelow returns a random integer N such that 0 <= N < 10

print(secrets.randbits(4)) # secrets.randbits returns an integer with k random bits example: 4 random bits values from 0 to 15

print(secrets.choice(mylist)) # secrets.choice returns a random element from a sequence




0
1
E


## numpy

In [36]:
import numpy as np

np.random.rand(3,2) # np.random.rand returns an array of specified shape and fills it with random values as per standard normal distribution

array([[0.66209333, 0.36237417],
       [0.13945055, 0.627853  ],
       [0.56264914, 0.13770174]])

In [37]:
np.random.randint(0, 10, size=(3, 3)) # np.random.randint returns an array of specified shape and fills it with random values as per uniform distribution over [low, high)

array([[4, 1, 4],
       [9, 2, 6],
       [8, 4, 5]])

In [38]:
mylist = list("ABCDEFGH")
np.random.shuffle(mylist) # np.random.shuffle shuffles the elements in the list in place

In [39]:
mylist

['B', 'E', 'A', 'H', 'D', 'F', 'C', 'G']

In [43]:
arr =np.array([[0.66209333, 0.36237417],
       [0.13945055, 0.627853  ],
       [0.56264914, 0.13770174]])

np.random.shuffle(arr) # np.random.shuffle shuffles the elements in the array in place. 

In [44]:
arr

array([[0.56264914, 0.13770174],
       [0.66209333, 0.36237417],
       [0.13945055, 0.627853  ]])

In [45]:
np.random.seed(10) # np.random.seed will generate the same random number every time we run the code

print(np.random.rand(3,2))
print(np.random.randint(0, 10, size=(3, 3)))
np.random.seed(10)
print(np.random.rand(3,2))
print(np.random.randint(0, 10, size=(3, 3)))


[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]]
[[1 8 9]
 [0 8 6]
 [4 3 0]]
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]]
[[1 8 9]
 [0 8 6]
 [4 3 0]]
